#!/usr/bin/env python
# -*- coding: utf8 -*-

# This file is part of Saywah.
# Copyright (C) 2009 Renzo Carbonara <gnuk0001@gmail.com>
#
# Saywah is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Saywah is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Saywah.  If not, see <http://www.gnu.org/licenses/>.


import logging
import optparse

import saywah.core.conf
import saywah.core.service
import saywah.core.dbus_services


log = logging.getLogger(__name__)


def parse_args():
    usage = u"usage: %prog [options] message"
    parser = optparse.OptionParser(usage)

    parser.add_option("--no-dbus-service",
            action="store_false", dest="dbus_service", default=True,
            help=u"don't start Saywah DBus service")

    parser.add_option("-v", "--verbose",
            action="store_true", dest="verbose", default=False,
            help=u"verbose output")

    parser.add_option("--debug",
            action="store_true", dest="debug", default=False,
            help=u"debug output")

    return parser.parse_args()


def main():
    opts, args = parse_args()

    log_level = logging.DEBUG if opts.debug \
                else logging.INFO if opts.verbose \
                else None # default
    saywah.core.conf.init(log_level=log_level)

    if opts.dbus_service:
        saywah.core.service.saywah_service.setup()
        saywah.core.dbus_services.start()

    import gobject
    loop = gobject.MainLoop()
    loop.run()

if __name__ == '__main__':
    main()
